### ISSUE TITLE
Pridavanie obed. menu

### ISSUE THREAD

**Issue by martinmroc** [stromaler/mcfood#19]
- [x] Pridat automaticky dni (prac. dni) , ak to bude moc zlozite, staci formular.
- [x] Dnes (obrazok na pozadi) vypisovat iba v danny den, cez vikend nic
- [x] Ak uz preslo par dni v dannom tyzdni, predchadzajuce dni dat .disabled (ak to bude moc takze ser nato)
- [x] 7 inputov na nazov jedla, vedla 7 inputov na cenu.

**Comment by stromaler** [comment]
@martinmroc classu disabled som dal na dni v minulosti ale vyzera to tak isto
